# fly.toml app configuration file generated for core-lane-rpc on 2025-11-17T09:30:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'core-lane-rpc'
primary_region = 'cdg'

[build]
  image = 'ghcr.io/lanelayer/core-lane/core-lane:latest'

[env]
  BITCOIN_CACHE_HOST = 'bitcoin-cache.internal'
  BITCOIN_CACHE_PORT = '8545'
  DATA_DIR = '/data'
  ELECTRUM_URL = 'ssl://electrum.blockstream.info:50002'
  HTTP_PORT = '8545'
  NETWORK = 'mainnet'
  ONLY_START = 'core-lane'
  

[[mounts]]
  source = 'core_lane_storage'
  destination = '/data'

[http_service]
  internal_port = 8545
  force_https = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '1m0s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
