# fly.toml app configuration file generated for bitcoin-cache on 2025-11-14T11:31:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bitcoin-cache'
primary_region = 'cdg'

[build]
  image = 'ghcr.io/lanelayer/core-lane/core-lane:latest'

[env]
  BITCOIN_CACHE_PORT = '8545' 
  CACHE_BIND_HOST = "::"
  BITCOIN_UPSTREAM_RPC_URL = 'https://bitcoin-rpc.publicnode.com'
  CACHE_DIR = '/storage/cache'
  DATA_DIR = '/storage/data'
  DISABLE_ARCHIVE_FETCH = 'true'
  ONLY_START = 'bitcoin-cache'
  RPC_PASSWORD = 'bitcoin123'
  RPC_USER = 'bitcoin'
  STARTING_BLOCK_COUNT = '916201'

[processes]
  app = '/app/entrypoint-rpc.sh'

[[mounts]]
  source = 'core_lane_storage'
  destination = '/storage'

[http_service]
  internal_port = 8545
  force_https = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '1m0s'
    method = 'get'
    path = '/health'
    protocol = 'http'



[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
