# fly.toml configuration for core-lane-cache-testnet4

app = "core-lane-cache-testnet4"
primary_region = "cdg"

[build]
  image = 'ghcr.io/lanelayer/core-lane/core-lane:latest'

[env]
  BITCOIN_CACHE_PORT = "8332"
  CACHE_BIND_HOST = "::"
  BITCOIN_UPSTREAM_RPC_URL = "http://94.130.161.17:8000"
  BLOCK_ARCHIVE_URL = ""
  DISABLE_ARCHIVE_FETCH = "true"
  ELECTRUM_URL = ""
  NETWORK = "testnet4"
  ONLY_START = "bitcoin-cache"
  RPC_PASSWORD = "bitcoin123"
  RPC_USER = "bitcoin"
  STARTING_BLOCK_COUNT = "111303"

[[mounts]]
  source = "core_lane_storage"
  destination = "/data"



[http_service]
  internal_port = 8332
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '1m0s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2